### ISSUE TITLE
How to check current offered version of Chromium?

### ISSUE THREAD

**Issue by snakyjake1** [henrypp/chrlauncher#109]
How do I check what the current version is of Chromium stable-nosync-codecs?

chrlauncher executes, but doesn't tell me what version of Chromium is offered:

![image](https://user-images.githubusercontent.com/8312560/47970714-03bb4980-e03e-11e8-803d-9c8de98aef8d.png)

**Comment by henrypp** [comment]
If new version is available, chrlauncher will tell you. If not then it's just closed.

**Comment by woolyss** [comment]
Hello snakyjake1,

`stable-nosync-codecs` and `dev-nosync-codecs` versions of Chromium are discontinued since June 2018.

Note from Nik (the developer) at https://chromium.woolyss.com/?all=1#comment-3574 (This link will load all comments on the site):
> between v68 and v69 there is a major changes in the chromium codebase (webrtc is integrated deeply in chromium).. Before this changes i did some patches (~5-10 files). After that changes the amount of files that had to be changed, increased ~10 times and still increase. So i don't have much time to patch the chromium each build, sorry =\

So choose another "No sync" version like `dev-clang-nosync`.

For info, to convert a "Sync" version into a "No sync" version, just change `setx GOOGLE_API_KEY "false"` (https://chromium.woolyss.com/#google-api-keys)

**Comment by snakyjake1** [comment]
How do you know what the other version are (e.g. dev-clang-nosync)?
I don't see them listed in chrlauncher.ini.

**Comment by snakyjake1** [comment]
Would it be a good idea for chrlauncher to inform the user that the version is discontinued?

**Comment by woolyss** [comment]
> I don't see them listed in chrlauncher.ini.

Search the parameter `ChromiumType=xxxxxxxxxx`
- in the **chrlauncher.ini** file : https://github.com/henrypp/chrlauncher/blob/master/bin/chrlauncher.ini
- and in the **Readme.txt** file : https://github.com/henrypp/chrlauncher/blob/master/bin/Readme.txt

> [...] to inform the user that the version is discontinued?

Agree. I made a commit at https://github.com/woolyss/chrlauncher/blob/patch-2/bin/Readme.txt

**Comment by henrypp** [comment]
>Discontinued since June 2018

@woolyss can you print all available types of chromium and it's description (include discontinued) here, please!

**Comment by woolyss** [comment]
Hi henry++,

Before all, thank you for your great work! ;)

Here the Chromium builds available in 32-bit and 64-bit:

* `dev-official`
Official development builds from snapshots repository
"storage.googleapis.com/chromium-browser-snapshots/index.html" (32/64 bit)
https://chromium.woolyss.com/api/v3/?os=windows&out=json&type=dev-official

* `dev-codecs-sync`	
Unofficial development builds with codecs
"github.com/henrypp/chromium/releases" (32/64 bit)
https://chromium.woolyss.com/api/v3/?os=windows&out=json&type=dev-codecs-sync

* `dev-clang-nosync`
Unofficial development builds without Google services
"github.com/RobRich999/Chromium_Clang/releases" (32/64 bit)
https://chromium.woolyss.com/api/v3/?os=windows&out=json&type=dev-clang-nosync

* `stable-codecs-sync`
Unofficial stable builds with codecs
"github.com/henrypp/chromium/releases" (32/64 bit)
https://chromium.woolyss.com/api/v3/?os=windows&out=json&type=stable-codecs-sync

* `ungoogled-chromium`
Unofficial builds without google integration and enhanced privacy
"github.com/Eloston/ungoogled-chromium" (32/64 bit)
https://chromium.woolyss.com/api/v3/?os=windows&out=json&type=ungoogled-chromium

-----------

Discontinued builds:

* `dev-codecs-nosync` **!!! DISCONTINUED since June 2018 !!!**
Unofficial development builds with codecs and without Google services
"github.com/henrypp/chromium/releases" (32/64 bit)
https://chromium.woolyss.com/api/v3/?os=windows&out=json&type=dev-codecs-nosync

* `stable-codecs-nosync` **!!! DISCONTINUED since June 2018 !!!**
Unofficial stable builds with codecs and without google services
"github.com/henrypp/chromium/releases" (32/64 bit)
https://chromium.woolyss.com/api/v3/?os=windows&out=json&type=stable-codecs-nosync

-----------

For info, I prepare another entry but it is not currently compatible with chrlauncher.
https://github.com/macchrome/winchrome/issues/3

* `dev-codecs-nosync-experimental` **!!! EXPERIMENTAL !!!**
Unofficial development builds with codecs and without Google services
"github.com/macchrome/winchrome/releases" (64 bit)
https://chromium.woolyss.com/api/v3/?os=windows&out=json&type=dev-codecs-nosync-experimental

**Comment by woolyss** [comment]
The `dev-codecs-nosync-experimental` works nicely! ^^
https://github.com/macchrome/winchrome/issues/3#issuecomment-440075690

Thank you very much to marmaduke and you.
Have good days!

**Comment by snakyjake1** [comment]
Why am I not getting this version:
![image](https://user-images.githubusercontent.com/8312560/49950807-5d205f00-fead-11e8-928a-c2888e5888d8.png)

I have these settings:
ChromiumType=ungoogled-chromium
ChromiumCheckPeriod=-1
ChromiumLastCheck=1544716360

My version is:
67.0.3396.99 (64-bit)

Thanks.

**Comment by henrypp** [comment]
@snakyjake1, i think [(its normal)](https://ungoogled-software.github.io/ungoogled-chromium-binaries/releases/windows/64bit/)

**Comment by henrypp** [comment]
@woolyss 2.5.4 supports  7z

**Comment by woolyss** [comment]
Thank you very much Henry. You are a master! ;)
