### ISSUE TITLE
Looses all settings/extensions whenever i run chrlauncher (in combo with ungoogled-chromium)

### ISSUE THREAD

**Issue by detra** [henrypp/chrlauncher#127]
Not sure if by design .. 
when using 'portable' edition of 
Chromium for 64-bit Windows @ `[chromium.woolyss.com](url)`
Reference: Google Chrome 72.0.3626.81 (612437) • Tuesday, 29 Jan 2019 >
>71.0.3578.98 (599034) • Thursday, 13 Dec 2018

I run chrlauncher when checking for an update it resets the whole profile and wipes settings/ext's etc..

**Comment by Innomen** [comment]
Honestly feels like it's by design. The entire chromium segment feels dominated by Google employees to me. Just compare the install/update experiences of chromium and firefox. It's like it all exists simply for the sake of place filling to prevent an actual competitor from springing up. Why else isn't there clear consensus? Why do we even need this weird updater launcher thing, why not just roll this function into chromium itself? Isn't the objective to compete with chrome? What does ungoogled even mean? What's the difference between chrome and "Googled" chromium?

Feels to me like the be companies have successfully invaded all the actually competitive and threatening open source browser projects. Chromium being no exception.

**Comment by henrypp** [comment]
chrlauncher is not change Chromium profile at any time. Here is answer #116.
