### ISSUE TITLE
No update since 74.0.3689.0 x64. Today release in chromium is 77.0.3846.0 x64 !!!

### ISSUE THREAD

**Issue by jpvaliquette** [henrypp/chrlauncher#139]
Even with chrlauncher.ini file in %APPDATA%\Henry++\chrlauncher

**Comment by johenning** [comment]
The problem is that the `dev-codecs-sync` type is still at [74.0.3689.0](https://chromium.woolyss.com/api/v3/?os=windows&bit=64&type=dev-codecs-sync&out=json).
If you need codecs I would suggest switching to `stable-codecs-sync` (which is at [75.0.3770.100](https://chromium.woolyss.com/api/v3/?os=windows&bit=64&type=stable-codecs-sync&out=json)) by editing the line 

    `ChromiumType=dev-codecs-sync`

in `chrlauncher.ini.` 
If you want the newest development build ([77.0.3855.0](https://chromium.woolyss.com/api/v3/?os=windows&bit=64&type=dev-official&out=json)) without codecs use `dev-official`. 

If no update is found after changing the type, try launching chrlauncher with the `/forcecheck` flag.

**Comment by pseisam** [comment]
I use stable-codecs-sync but Nik is not releasing any new versions anymore. How can I switch to another stable build with codeces included (e.g. marmaduke)?

**Comment by johenning** [comment]
@pseisam You could use ```ungoogled-chromium``` doesn't have sync but has all codecs

**Comment by henrypp** [comment]
@pseisam @johenning @jpvaliquette 

Nothing need to change:

https://github.com/henrypp/chrlauncher/issues/142#issuecomment-518353370
