### ISSUE TITLE
Usage behind proxy server fails

### ISSUE THREAD

**Issue by jachstet-sea** [henrypp/chrlauncher#17]
Hello, I'm trying to use the tool in a network that filters all traffic through a proxy server. Internet Explorer uses a proy auto-configuration file (pac-script) and I expected chrlauncher to just work since it uses the WinInet-functions. However, according to wireshark, a direct connection to the target HTTP-server is attempted, which fails due to the firewall blocking the request.

Has anyone succeeded running chrlauncher through a proxy server?

**Comment by J3ph42** [comment]
Also behind a proxy that we use a pac script for, get error "Updates  not found for <build> configuration." when I launch chrlauncher. Can manually reach a URL https://github.com/henrypp/chromium/releases/download/<version>/<build>.zip
and download it though.

**Comment by henrypp** [comment]
fixed (i hope!).

**Comment by superbob** [comment]
It doesn't work for me.

When I start chrlauncher for the first time I see the "_No updates found for "Chromium 64-bit (stable-codecs-sync)"_" message and then "_Unable to start browser. (null)_" error message which closes the app afterwards.

In wireshark I see multiple requests performed:

At first it works fine: proxy is taken into account and authentication (user/pasword) is transmitted correctly.

A request to `https://chromium.woolyss.com/api/v3/?os=windows&bit=64&type=stable-codecs-sync&out=string` is done and it returns the correct value.

But then, a CONNECT request is performed to github.
Request to `/wpad.dat` and subdomains of digicert.com (such as `GET http://crl4.digicert.com/DigiCertHighAssuranceEVRootCA.crl`) are performed repeatedly.

_wpad_ requests works fine, but all _digicert.com_ requests fails with "407 Proxy Authentication Required" because credentials are not passed. It's strange because the first request pass credentials correctly.
