### ISSUE TITLE
The directory name is invalid

### ISSUE THREAD

**Issue by Suncatcher** [henrypp/chrlauncher#43]
This box popup after the first download of Chromium with your app. 

![6](https://cloud.githubusercontent.com/assets/6388034/20176771/66c29e62-a75a-11e6-97c7-fa5b67d02ac5.PNG)

I tried dozens of directories (ProgramData, Program Files, Program Files x86, etc) but the message still popup. I also renamed the folder in a variety of ways and still result is the same.

I tried to reinstall with different channel type (from dev-codecs-sync to stable-codecs-sync) and it started to throw error. I have no idea what have changed after that.

**Comment by henrypp** [comment]
попробуй ничего не изменять в chrlauncher.ini, используй настройки и пути по умолчанию.
если не поможет, то попробуй переместить папку сабжа в папку без пробелов _"C:\НоваяПапка"_

**Comment by Suncatcher** [comment]
Well, I just cleaned all via registry file, copied original folder with **untouched** *crlauncher.ini* to "c:\Program Files\64\" and got the same error. The problem is out there.

**Comment by Suncatcher** [comment]
It went fine after I put it in C root. 
Funny but previously it worked from `Program Files` like a charm. Cannot understand what caused the issue.

**Comment by ebauch** [comment]
I got the same problem. An error was thrown.

Copying it to the C: dir (instead of program files) solved it.

**Comment by henrypp** [comment]
i try fix it

**Comment by henrypp** [comment]
First. Chromium has no feature to write into profile directory placed at "Program Files" because it's UAC directory without rights to write and out WITHOUT alerts. If you saving Chromium in "Program Files" you need to change profile directory where Chromium was allowed to write (like %LOCALAPPDATA%).
Second, i was fixed running Chromium from directories with spaces. Please wait for new release!
